### ISSUE TITLE
Prefabs error after decimate

### ISSUE THREAD

**Issue by eddyugi** [Whinarn/MeshDecimator#18] opened 2019-11-28 23:22 UTC
If create prefab with a gameobject after decimate, the prefab has wrong , 
not includes lods renderer. 
How to fix this?

**Comment by Whinarn** [comment] 2019-12-07 08:59
@eddyugi I'm not entirely sure what you are asking. What is your expected behavior and what is the actual behavior?

**Comment by eddyugi** [comment] 2019-12-07 12:17
![Sem título](https://user-images.githubusercontent.com/12818841/70374545-4949e600-18d2-11ea-9c0d-5f681d59df18.png)


![Decimate_Error](https://user-images.githubusercontent.com/12818841/70374518-ea846c80-18d1-11ea-929c-f0e963b70162.png)

**Comment by Whinarn** [comment] 2019-12-07 12:24
I understand your problem now.
This issue is essentially a duplicate of this one: https://github.com/Whinarn/MeshDecimator/issues/14
As you can see from my answers there, this is because the example scripts are not dealing with this properly. I suggest using [UnityMeshSimplifier](https://github.com/Whinarn/UnityMeshSimplifier) for Unity instead. It's my other project that spawned from this one that was specifically made for Unity.

**Closed as completed** 2019-12-10 20:49 UTC
